{
	"version": 1630930009,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/vendingmac-sheet0.png",
		"images/gameobj1-sheet0.png",
		"images/btng1-sheet0.png",
		"images/blocky-sheet0.png",
		"images/taggm1-sheet0.png",
		"images/taggm1-sheet1.png",
		"images/lightgm1-sheet0.png",
		"images/correctionhand-sheet0.png",
		"images/correctionhand-sheet1.png",
		"images/correctionhand-sheet2.png",
		"images/bgg2-sheet0.png",
		"images/gobj2-sheet0.png",
		"images/gobj2-sheet1.png",
		"images/questbox-sheet0.png",
		"images/bg1-sheet0.png",
		"images/bgmap-sheet0.png",
		"images/boy-sheet0.png",
		"images/boy-sheet1.png",
		"images/gamepad-sheet0.png",
		"images/gamepad-sheet1.png",
		"images/control-sheet0.png",
		"images/block-sheet0.png",
		"images/knife-sheet0.png",
		"images/knife-sheet1.png",
		"images/gamepad2-sheet0.png",
		"images/gamepad2-sheet1.png",
		"images/bgoption-sheet0.png",
		"images/btn-sheet0.png",
		"images/btn-sheet1.png",
		"images/menu-sheet0.png",
		"images/menu-sheet1.png",
		"images/minimap-sheet0.png",
		"images/return-sheet0.png",
		"images/shadow-sheet0.png",
		"media/sweet talks – limujii (no copyright music).m4a",
		"media/sweet talks – limujii (no copyright music).ogg",
		"media/vending machine.m4a",
		"media/vending machine.ogg",
		"media/atm.m4a",
		"media/atm.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}