{
	"version": 1630845719,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/bg1-sheet0.png",
		"images/bgmap-sheet0.png",
		"images/boy-sheet0.png",
		"images/boy-sheet1.png",
		"images/gamepad-sheet0.png",
		"images/gamepad-sheet1.png",
		"images/control-sheet0.png",
		"images/block-sheet0.png",
		"images/knife-sheet0.png",
		"images/knife-sheet1.png",
		"images/gamepad2-sheet0.png",
		"images/gamepad2-sheet1.png",
		"images/bgoption-sheet0.png",
		"images/btn-sheet0.png",
		"images/btn-sheet1.png",
		"images/menu-sheet0.png",
		"images/menu-sheet1.png",
		"images/menu-sheet2.png",
		"images/minimap-sheet0.png",
		"media/sweet talks – limujii (no copyright music).m4a",
		"media/sweet talks – limujii (no copyright music).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}